version: "3.8"
services:
  web:
    # Hope this will change
    image: etudiants:1.0
    container_name: etudiants
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - "db"
    networks:
      - net_etudiants1.0

  db:
    image: mysql:9.0
    container_name: db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: etudiants
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - net_etudiants1.0

  adminer:
    image: adminer
    container_name: phpmyadmin
    restart: always
    ports:
      - 3001:8080

networks:
  net_etudiants1.0: