name: WELCOME-MESSAGE-AWS

on:
  workflow_run:
    workflows: ["PUSH_TO_DOCKERHUB"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Welcome message
        run: echo "Welcome back to my channels"

      # - name: Pull docker image
      #   run: sudo docker pull devcloudarmel/etudiants:latest

      # - name: Delete old container
      #   run: sudo docker rm -f etudiants-container || true
      
      # - name: Run docker container
      #   run: sudo docker run -d -p 3306:3306 --name etudiants-container devcloudarmel/etudiants:latest
