name: PUSH_TO_DOCKERHUB

on: 
  pull_request: 
    branches: 
      - main

jobs:
  buid:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the docker image
      run: docker build -t devcloudarmel/etudiants:1.0 .

    - name: Push to docker hub
      run: docker push devcloudarmel/etudiants:1.0